services:
  - type: web
    name: face-auth-backend
    env: python
    buildCommand: apt-get update && apt-get install -y libsm6 libxext6 libxrender-dev && pip install numpy==1.23.5 && pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: CORS_ORIGIN
        value: "http://localhost:3000"
